### ISSUE TITLE
The repo intro should incorrect link

### ISSUE THREAD

**Issue by mocheng** [revolunet/react-load-umd#1]
The link should be http://revolunet.github.io/react-umd-loader instead of http://revolunet.github.io/reactumd-loader .

![image](https://user-images.githubusercontent.com/239291/33694827-3be88d7c-db35-11e7-88f8-c4d7f9d81c95.png)

Nice work for this UMD idea！

**Comment by revolunet** [comment]
thanks for reporting, fixed 👍
